#ifndef __SAMPLER_RASPBERRY__
#define __SAMPLER_RASPBERRY__

#include "raspberry_pins.h"

#define PIN_BANK_SELECT_LEFT        RPI_PIN_15
#define PIN_BANK_SELECT_RIGHT       RPI_PIN_14

#define PIN_BANK_STATUS             RPI_PIN_18

#define PIN_BANK_LOAD               RPI_PIN_23
#define PIN_BANK_SAVE               RPI_PIN_24

#define PIN_SAMPLE_SELECT_LEFT      RPI_PIN_08
#define PIN_SAMPLE_SELECT_RIGHT     RPI_PIN_25
#define PIN_SAMPLE_MODE             RPI_PIN_07
#define PIN_SAMPLE_MIDI_SET         RPI_PIN_12
#define PIN_SAMPLE_MIDI_STATUS      RPI_PIN_01

#define PIN_SAMPLE_PLAY             RPI_PIN_16

#define PIN_CONTROL_01_LEFT         RPI_PIN_17
#define PIN_CONTROL_01_RIGHT        RPI_PIN_04
#define PIN_CONTROL_02_LEFT         RPI_PIN_22
#define PIN_CONTROL_02_RIGHT        RPI_PIN_27
#define PIN_CONTROL_03_LEFT         RPI_PIN_09
#define PIN_CONTROL_03_RIGHT        RPI_PIN_10
#define PIN_CONTROL_04_LEFT         RPI_PIN_05
#define PIN_CONTROL_04_RIGHT        RPI_PIN_11
#define PIN_CONTROL_05_LEFT         RPI_PIN_13
#define PIN_CONTROL_05_RIGHT        RPI_PIN_06
#define PIN_CONTROL_06_LEFT         RPI_PIN_26
#define PIN_CONTROL_06_RIGHT        RPI_PIN_19

#define PIN_CONTROL_SELECT_LEFT     RPI_PIN_21
#define PIN_CONTROL_SELECT_RIGHT    RPI_PIN_20

#endif
