#ifndef __SAMPLER_RASPBERRY__
#define __SAMPLER_RASPBERRY__

#include "raspberry_pins.h"

#define CONTROL_BANK_ID_LEFT        RPI_PIN_14
#define CONTROL_BANK_ID_RIGHT       RPI_PIN_15
#define CONTROL_BANK_LOAD_SAVE      RPI_PIN_18

#define CONTROL_SAMPLE_ID_LEFT      RPI_PIN_23
#define CONTROL_SAMPLE_ID_RIGHT     RPI_PIN_24
#define CONTROL_SAMPLE_MODE         RPI_PIN_25
#define CONTROL_SAMPLE_MIDI         RPI_PIN_08

#define CONTROL_SAMPLE_PLAY         RPI_PIN_07

#endif
